source("R/packages.R")
source("R/targets_config.R")
source("R/targets_pipeline.R")
source("R/app_targets.R")
source("R/app_utils.R")
source("R/transient.R")
source("R/control.R")
source("R/project.R")
source("R/process.R")
source("R/results.R")
source("R/logs.R")
source("R/ui.R")
source("R/server.R")
shinyApp(ui = ui, server = server)
